version: '3.8'

services:
  backend:
    build: .
    container_name: my_backend
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_USER: fitrah
      DB_PASSWORD: lolrandom
      DB_NAME: catalog
      DB_PORT: 5432
    ports:
      - "5000:5000"
    command: ["sh", "-c", "sleep 5 && /root/backend migrate && /root/backend"]
    networks:
      - backend_network

networks:
  backend_network:
    external: true