# Stage 1: Build
FROM node:16-alpine AS build
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy source code
COPY . .

# Build aplikasi untuk production
RUN npm run build

# Stage 2: Run
FROM node:16-alpine
WORKDIR /app

# Install alat untuk menjalankan aplikasi (optional)
RUN apk add --no-cache curl bash

# Copy build dari tahap build
COPY --from=build /app/build ./build

# Install server untuk static files
RUN npm install -g serve

# Expose port aplikasi
EXPOSE 3000

# Jalankan aplikasi dengan server production
CMD ["serve", "-s", "build", "-l", "3000"]