# Gunakan Node.js 16 resmi
FROM node:16

# Buat direktori kerja di dalam container
WORKDIR /app

# Salin file package.json dan package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Salin seluruh source code ke dalam container
COPY . .

# Build aplikasi
RUN npm run build

# Jalankan aplikasi
CMD ["npm", "start"]
