---
- name: Pastikan direktori Jenkins tersedia
  file:
    path: /home/jenkinsandmonitoring/jenkins
    state: directory
    mode: '0755'

- name: Copy Jenkins Docker Compose Template
  template:
    src: docker-compose.yml.j2
    dest: /home/jenkinsandmonitoring/jenkins/docker-compose.yml
    mode: '0644'

- name: Start Jenkins Container
  shell: |
    cd /home/jenkinsandmonitoring/jenkins
    docker compose up -d --build
