---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy konfigurasi Nginx untuk Reverse Proxy
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Aktifkan konfigurasi Nginx
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Restart Nginx

- name: Pastikan Nginx berjalan
  service:
    name: nginx
    state: started
    enabled: yes

- name: Reload Nginx untuk menerapkan perubahan
  command: nginx -t
  register: nginx_config_check
  changed_when: nginx_config_check.rc != 0
  failed_when: nginx_config_check.rc != 0

- name: Restart Nginx jika konfigurasi valid
  service:
    name: nginx
    state: restarted
  when: nginx_config_check.rc == 0
