- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Pastikan Nginx service tersedia dan berjalan
  shell: |
    systemctl enable nginx
    systemctl start nginx
  ignore_errors: yes

- name: Cek nama service Nginx
  shell: systemctl list-units --type=service | grep nginx | awk '{print $1}'
  register: nginx_service_name
  changed_when: false

- name: Debug nama service Nginx
  debug:
    var: nginx_service_name.stdout_lines

- name: Restart Nginx dengan nama service yang ditemukan
  service:
    name: "{{ nginx_service_name.stdout }}"
    state: restarted
  when: nginx_service_name.stdout | length > 0
  ignore_errors: yes
