version: '3.8'

services:
  frontend:
    image: fitrah.studentdumbways.my.id/frontend:1.0.0
    container_name: my_frontend
    restart: always
    environment:
      #- REACT_APP_BASEURL=http://localhost:5000/api/v1
      - PORT=3000
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend_network
    command: ["npm", "start"]

networks:
  backend_network:
    external: true