---
- name: Copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Copy Reverse Proxy Config for Jenkins
  template:
    src: jenkins.conf.j2
    dest: /etc/nginx/sites-available/jenkins
  notify: Restart Nginx

- name: Copy Reverse Proxy Config for Grafana
  template:
    src: grafana.conf.j2
    dest: /etc/nginx/sites-available/grafana
  notify: Restart Nginx

- name: Copy Reverse Proxy Config for Prometheus
  template:
    src: prometheus.conf.j2
    dest: /etc/nginx/sites-available/prometheus
  notify: Restart Nginx

- name: Copy Reverse Proxy Config for Node Exporter
  template:
    src: node_exporter.conf.j2
    dest: /etc/nginx/sites-available/node_exporter
  notify: Restart Nginx

- name: Enable sites
  file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  loop:
    - jenkins
    - grafana
    - prometheus
    - node_exporter
  notify: Restart Nginx
