---
- name: Copy Monitoring Docker Compose Template
  template:
    src: monitoring-compose.yml.j2
    dest: /home/jenkinsandmonitoring/monitoring/docker-compose.yml
    mode: '0644'

- name: Start Monitoring Containers
  shell: |
    cd /home/jenkinsandmonitoring/monitoring
    docker compose up -d --build
