---
- name: Pastikan direktori Monitoring tersedia
  file:
    path: /home/jenkinsandmonitoring/monitoring
    state: directory
    mode: '0755'

- name: Copy Monitoring Docker Compose Template
  template:
    src: monitoring-compose.yml.j2
    dest: /home/jenkinsandmonitoring/monitoring/docker-compose.yml
    mode: '0644'

- name: Start Monitoring Containers
  shell: |
    cd /home/jenkinsandmonitoring/monitoring
    docker compose up -d --build
