- name: Copy file konfigurasi monitoring
  template:
    src: monitoring-docker-compose.yml.j2
    dest: /home/deploy/monitoring/docker-compose.yml
    owner: deploy
    group: deploy
    mode: '0644'

- name: Jalankan monitoring dengan Docker Compose
  command: docker-compose up -d
  args:
    chdir: /home/deploy/monitoring
