---
- name: Pastikan direktori monitoring tersedia
  file:
    path: "/home/deploy/monitoring"
    state: directory
    owner: deploy
    group: deploy
    mode: '0755'

- name: Copy file konfigurasi monitoring
  template:
    src: "monitoring-compose.yml.j2"
    dest: "/home/deploy/monitoring/docker-compose.yml"
    owner: deploy
    group: deploy
    mode: '0644'

- name: Jalankan monitoring dengan Docker Compose
  become: yes
  become_user: deploy
  shell: |
    if command -v docker-compose &> /dev/null; then
      docker-compose up -d --build
    else
      docker compose up -d --build
    fi
  args:
    chdir: /home/deploy/monitoring
