---
# Install Certbot melalui Snap
- name: Install Certbot via Snap
  command: sudo snap install --classic certbot
  become: yes

# Cek apakah symlink Certbot sudah ada di /usr/bin
- name: Cek apakah symlink Certbot sudah ada di /usr/bin
  stat:
    path: /usr/bin/certbot
  register: certbot_symlink_check
  become: yes

# Buat symlink Certbot di /usr/bin jika belum ada
- name: Buat symlink Certbot di /usr/bin
  command: sudo ln -s /snap/bin/certbot /usr/bin/certbot
  when: certbot_symlink_check.stat.exists == false
  become: yes

# Setel Certbot agar dapat menggunakan plugin dengan root
- name: Setel Certbot agar dapat menggunakan plugin dengan root
  command: sudo snap set certbot trust-plugin-with-root=ok
  become: yes

# Install plugin Cloudflare untuk Certbot
- name: Install plugin Cloudflare untuk Certbot
  command: sudo snap install certbot-dns-cloudflare
  become: yes

# Buat direktori .secret untuk Cloudflare Token
- name: Buat direktori .secret untuk Cloudflare Token
  file:
    path: /root/.secret
    state: directory
    mode: '0700'
  become: yes

# Salin file template cloudflare.ini ke lokasi yang benar
- name: Salin file template cloudflare.ini
  template:
    src: cloudflare.ini.j2
    dest: /root/.secret/cloudflare.ini
    mode: '0600'
  become: yes

# Install permission file Cloudflare Token
- name: Setel permission file cloudflare.ini
  file:
    path: /root/.secret/cloudflare.ini
    mode: '0600'
  become: yes

# Cek apakah sertifikat SSL sudah ada untuk domain
- name: Cek apakah sertifikat SSL sudah ada untuk domain
  stat:
    path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
  register: ssl_check
  become: yes

# Generate Wildcard SSL Certificate jika belum ada
- name: Generate Wildcard SSL Certificate menggunakan Cloudflare DNS Challenge
  command: >
    sudo certbot certonly --dns-cloudflare
    --dns-cloudflare-credentials /root/.secret/cloudflare.ini
    -d '*.{{ domain_name }}' -d '{{ domain_name }}' --agree-tos --email {{ email_ssl }} --no-eff-email
  when: ssl_check.stat.exists == false
  become: yes
  register: ssl_output

# Tampilkan hasil eksekusi Certbot jika terjadi error
- name: Tampilkan hasil eksekusi Certbot jika terjadi error
  debug:
    var: ssl_output.stderr_lines
  when: ssl_output is defined and ssl_output.rc != 0
  become: yes

# Tampilkan hasil sertifikat jika berhasil
- name: Tampilkan hasil sertifikat SSL jika berhasil
  debug:
    msg: "Sertifikat SSL telah dibuat untuk domain: {{ domain_name }}"
  when: ssl_output.rc == 0
  become: yes
