---

# Install Certbot melalui Snap
- name: Install Certbot via Snap
  command: sudo snap install --classic certbot
  become: yes

# Buat symlink untuk Certbot di /usr/bin
- name: Buat symlink Certbot di /usr/bin
  command: sudo ln -s /snap/bin/certbot /usr/bin/certbot
  become: yes

# Setel Certbot agar dapat menggunakan plugin dengan root
- name: Setel Certbot agar dapat menggunakan plugin dengan root
  command: sudo snap set certbot trust-plugin-with-root=ok
  become: yes

# Install plugin Cloudflare untuk Certbot
- name: Install plugin Cloudflare untuk Certbot
  command: sudo snap install certbot-dns-cloudflare
  become: yes

# Buat direktori .secret untuk Cloudflare Token
- name: Buat direktori .secret untuk Cloudflare Token
  file:
    path: /root/.secret
    state: directory
    mode: '0700'
  become: yes

# Salin file template cloudflare.ini ke lokasi yang benar
- name: Salin file template cloudflare.ini
  template:
    src: cloudflare.ini.j2
    dest: /root/.secret/cloudflare.ini
    mode: '0600'
  become: yes

# Install permission file Cloudflare Token
- name: Setel permission file cloudflare.ini
  file:
    path: /root/.secret/cloudflare.ini
    mode: '0600'
  become: yes

# Generate Wildcard SSL Certificate menggunakan Cloudflare DNS Challenge
- name: Generate Wildcard SSL Certificate menggunakan Cloudflare DNS Challenge
  command: >
    sudo certbot certonly --dns-cloudflare
    --dns-cloudflare-credentials /root/.secret/cloudflare.ini
    -d '*.fitrah.studentdumbways.my.id' -d 'fitrah.studentdumbways.my.id'
  become: yes
  register: ssl_output

# Tampilkan hasil eksekusi Certbot jika terjadi error
- name: Tampilkan hasil eksekusi Certbot jika terjadi error
  debug:
    var: ssl_output.stderr_lines
  when: ssl_output.rc != 0
  become: yes
