- name: Deploy Prometheus
  shell: |
    docker run -d --name prometheus -p 9090:9090 prom/prometheus

- name: Deploy Node Exporter
  shell: |
    docker run -d --name node_exporter -p 9100:9100 prom/node-exporter

- name: Deploy Grafana
  shell: |
    docker run -d --name grafana -p 3000:3000 grafana/grafana
