# Add new user
- name: Create a new user
  user:
    name: newuser
    password: "{{ 'password' | password_hash('sha512') }}"
    groups: sudo
    append: yes

- name: Add SSH key for new user
  authorized_key:
    user: newuser
    key: "{{ lookup('file', '/.ssh/') }}"

- name: Update apt cache
  apt:
    update_cache: yes

