version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: fitrah
      POSTGRES_PASSWORD: lolrandom
      POSTGRES_DB: catalog
    volumes:
      - /home/$USER/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network

networks:
  backend_network:
    external: true
