- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisites for Docker
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create directory for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to Apt sources
  copy:
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'

- name: Update apt cache after adding Docker repository
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-compose
    state: present

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes