---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx reverse proxy
  template:
    src: reverse_proxy.conf.j2
    dest: /etc/nginx/sites-available/{{ domain_name }}
  notify: Reload Nginx

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/{{ domain_name }}
    dest: /etc/nginx/sites-enabled/{{ domain_name }}
    state: link
  notify: Reload Nginx

- name: Install Certbot
  snap:
    name: certbot
    classic: yes

- name: Generate SSL certificate
  command: certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos --email {{ certbot_email }}

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded