---
# Pastikan Nginx diinstal
- name: Install Nginx jika belum ada
  apt:
    name: nginx
    state: present

# Pastikan direktori konfigurasi Nginx tersedia
- name: Pastikan direktori untuk konfigurasi Nginx tersedia
  file:
    path: /etc/nginx/sites-available
    state: directory
    mode: '0755'

# Salin konfigurasi Nginx
- name: Salin konfigurasi Nginx untuk Reverse Proxy Frontend
  template:
    src: frontend.conf.j2
    dest: /etc/nginx/sites-available/frontend.conf
  notify: Restart Nginx

# Aktifkan konfigurasi Nginx
- name: Aktifkan konfigurasi Reverse Proxy untuk Frontend
  file:
    src: /etc/nginx/sites-available/frontend.conf
    dest: /etc/nginx/sites-enabled/frontend.conf
    state: link
  notify: Restart Nginx

# Pastikan konfigurasi Nginx valid sebelum restart
- name: Pastikan konfigurasi Nginx valid sebelum restart
  command: nginx -t
  register: nginx_config_check
  changed_when: nginx_config_check.rc != 0
  failed_when: nginx_config_check.rc != 0
  notify: Restart Nginx