---
- name: Perbarui daftar paket sebelum instalasi
  become: yes
  apt:
    update_cache: yes

- name: Install Nginx jika belum ada
  become: yes
  apt:
    name: nginx
    state: present

- name: Cek apakah Nginx dapat berjalan tanpa error
  become: yes
  command: nginx -t
  register: nginx_check
  changed_when: nginx_check.rc != 0
  failed_when: nginx_check.rc != 0

- name: Pastikan Nginx service tersedia dan berjalan
  become: yes
  shell: |
    systemctl enable nginx || true
    systemctl start nginx || true
  ignore_errors: yes

- name: Cek nama service Nginx
  become: yes
  shell: systemctl list-units --type=service | grep nginx | awk '{print $1}'
  register: nginx_service_name
  changed_when: false

- name: Debug nama service Nginx
  debug:
    var: nginx_service_name.stdout_lines

# ✅ Tambahkan Task untuk Membuat Direktori yang Hilang
- name: Pastikan direktori untuk konfigurasi Nginx tersedia
  become: yes
  file:
    path: /etc/nginx/sites-available
    state: directory
    mode: '0755'

- name: Salin konfigurasi Nginx untuk Reverse Proxy Frontend
  become: yes
  template:
    src: frontend.conf.j2
    dest: /etc/nginx/sites-available/frontend.conf
  notify: Restart Nginx

- name: Aktifkan konfigurasi Reverse Proxy untuk Frontend
  become: yes
  file:
    src: /etc/nginx/sites-available/frontend.conf
    dest: /etc/nginx/sites-enabled/frontend.conf
    state: link
  notify: Restart Nginx

- name: Pastikan konfigurasi Nginx valid sebelum restart
  become: yes
  command: nginx -t
  register: nginx_config_check
  changed_when: nginx_config_check.rc != 0
  failed_when: nginx_config_check.rc != 0
  notify: Restart Nginx

- name: Restart Nginx dengan nama service yang ditemukan
  become: yes
  service:
    name: "{{ nginx_service_name.stdout | default('nginx') }}"
    state: restarted
  when: nginx_service_name.stdout is defined and nginx_service_name.stdout | length > 0
  ignore_errors: yes