---
- name: Tambahkan user baru
  user:
    name: deploy
    password: "{{ '123' | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    createhome: yes

- name: Setup SSH Key untuk user deploy
  authorized_key:
    user: deploy
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Tambahkan user deploy ke sudoers
  lineinfile:
    path: /etc/sudoers.d/deploy
    create: yes
    line: 'deploy ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
