- name: Pastikan Docker Compose terinstal
  apt:
    name: docker-compose
    state: present
    update_cache: yes

- name: Clone repository frontend dari GitHub
  git:
    repo: "https://github.com/dumbwaysdev/literature-frontend.git"
    dest: "/home/deploy/literature-frontend"
    version: main
    force: yes
  become_user: deploy

- name: Salin Dockerfile ke direktori frontend
  template:
    src: Dockerfile.j2
    dest: "/home/deploy/literature-frontend/Dockerfile"
    owner: deploy
    group: deploy
    mode: '0644'

- name: Salin docker-compose.yml ke direktori frontend
  template:
    src: docker-compose.yml.j2
    dest: "/home/deploy/literature-frontend/docker-compose.yml"
    owner: deploy
    group: deploy
    mode: '0644'

- name: Bangun dan jalankan aplikasi frontend dengan Docker Compose
  command: docker-compose up -d --build
  args:
    chdir: /home/deploy/literature-frontend
  become_user: deploy
